/*
Copyright 2019 The LB Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package v1

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServerList struct {
	Metadata             *ListMeta `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Items                []*Server `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ServerList) Reset()         { *m = ServerList{} }
func (m *ServerList) String() string { return proto.CompactTextString(m) }
func (*ServerList) ProtoMessage()    {}
func (*ServerList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *ServerList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerList.Unmarshal(m, b)
}
func (m *ServerList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerList.Marshal(b, m, deterministic)
}
func (m *ServerList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerList.Merge(m, src)
}
func (m *ServerList) XXX_Size() int {
	return xxx_messageInfo_ServerList.Size(m)
}
func (m *ServerList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerList.DiscardUnknown(m)
}

var xxx_messageInfo_ServerList proto.InternalMessageInfo

func (m *ServerList) GetMetadata() *ListMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ServerList) GetItems() []*Server {
	if m != nil {
		return m.Items
	}
	return nil
}

type Server struct {
	Metadata             *ObjectMeta   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec                 *ServerSpec   `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status               *ServerStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Server) Reset()         { *m = Server{} }
func (m *Server) String() string { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()    {}
func (*Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server.Unmarshal(m, b)
}
func (m *Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server.Marshal(b, m, deterministic)
}
func (m *Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server.Merge(m, src)
}
func (m *Server) XXX_Size() int {
	return xxx_messageInfo_Server.Size(m)
}
func (m *Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Server.DiscardUnknown(m)
}

var xxx_messageInfo_Server proto.InternalMessageInfo

func (m *Server) GetMetadata() *ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Server) GetSpec() *ServerSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Server) GetStatus() *ServerStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ServerSpec struct {
	// endpoint ips/hostnames
	Endpoints            []string      `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Ports                []*ServerPort `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ServerSpec) Reset()         { *m = ServerSpec{} }
func (m *ServerSpec) String() string { return proto.CompactTextString(m) }
func (*ServerSpec) ProtoMessage()    {}
func (*ServerSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{2}
}

func (m *ServerSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerSpec.Unmarshal(m, b)
}
func (m *ServerSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerSpec.Marshal(b, m, deterministic)
}
func (m *ServerSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerSpec.Merge(m, src)
}
func (m *ServerSpec) XXX_Size() int {
	return xxx_messageInfo_ServerSpec.Size(m)
}
func (m *ServerSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ServerSpec proto.InternalMessageInfo

func (m *ServerSpec) GetEndpoints() []string {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *ServerSpec) GetPorts() []*ServerPort {
	if m != nil {
		return m.Ports
	}
	return nil
}

type ServerPort struct {
	Port int32 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	// tcp or udp
	Protocol             string   `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerPort) Reset()         { *m = ServerPort{} }
func (m *ServerPort) String() string { return proto.CompactTextString(m) }
func (*ServerPort) ProtoMessage()    {}
func (*ServerPort) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{3}
}

func (m *ServerPort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerPort.Unmarshal(m, b)
}
func (m *ServerPort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerPort.Marshal(b, m, deterministic)
}
func (m *ServerPort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerPort.Merge(m, src)
}
func (m *ServerPort) XXX_Size() int {
	return xxx_messageInfo_ServerPort.Size(m)
}
func (m *ServerPort) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerPort.DiscardUnknown(m)
}

var xxx_messageInfo_ServerPort proto.InternalMessageInfo

func (m *ServerPort) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ServerPort) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

type ServerStatus struct {
	Conditions           []*Condition     `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Ingress              []*ServerIngress `protobuf:"bytes,2,rep,name=ingress,proto3" json:"ingress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ServerStatus) Reset()         { *m = ServerStatus{} }
func (m *ServerStatus) String() string { return proto.CompactTextString(m) }
func (*ServerStatus) ProtoMessage()    {}
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{4}
}

func (m *ServerStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStatus.Unmarshal(m, b)
}
func (m *ServerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStatus.Marshal(b, m, deterministic)
}
func (m *ServerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStatus.Merge(m, src)
}
func (m *ServerStatus) XXX_Size() int {
	return xxx_messageInfo_ServerStatus.Size(m)
}
func (m *ServerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStatus proto.InternalMessageInfo

func (m *ServerStatus) GetConditions() []*Condition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *ServerStatus) GetIngress() []*ServerIngress {
	if m != nil {
		return m.Ingress
	}
	return nil
}

type ServerIngress struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerIngress) Reset()         { *m = ServerIngress{} }
func (m *ServerIngress) String() string { return proto.CompactTextString(m) }
func (*ServerIngress) ProtoMessage()    {}
func (*ServerIngress) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{5}
}

func (m *ServerIngress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerIngress.Unmarshal(m, b)
}
func (m *ServerIngress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerIngress.Marshal(b, m, deterministic)
}
func (m *ServerIngress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerIngress.Merge(m, src)
}
func (m *ServerIngress) XXX_Size() int {
	return xxx_messageInfo_ServerIngress.Size(m)
}
func (m *ServerIngress) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerIngress.DiscardUnknown(m)
}

var xxx_messageInfo_ServerIngress proto.InternalMessageInfo

func (m *ServerIngress) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

// Requests/Responses
type ServerListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerListRequest) Reset()         { *m = ServerListRequest{} }
func (m *ServerListRequest) String() string { return proto.CompactTextString(m) }
func (*ServerListRequest) ProtoMessage()    {}
func (*ServerListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{6}
}

func (m *ServerListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerListRequest.Unmarshal(m, b)
}
func (m *ServerListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerListRequest.Marshal(b, m, deterministic)
}
func (m *ServerListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerListRequest.Merge(m, src)
}
func (m *ServerListRequest) XXX_Size() int {
	return xxx_messageInfo_ServerListRequest.Size(m)
}
func (m *ServerListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServerListRequest proto.InternalMessageInfo

type ServerShowRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerShowRequest) Reset()         { *m = ServerShowRequest{} }
func (m *ServerShowRequest) String() string { return proto.CompactTextString(m) }
func (*ServerShowRequest) ProtoMessage()    {}
func (*ServerShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{7}
}

func (m *ServerShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerShowRequest.Unmarshal(m, b)
}
func (m *ServerShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerShowRequest.Marshal(b, m, deterministic)
}
func (m *ServerShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerShowRequest.Merge(m, src)
}
func (m *ServerShowRequest) XXX_Size() int {
	return xxx_messageInfo_ServerShowRequest.Size(m)
}
func (m *ServerShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServerShowRequest proto.InternalMessageInfo

func (m *ServerShowRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ServerList)(nil), "lb.api.v1.ServerList")
	proto.RegisterType((*Server)(nil), "lb.api.v1.Server")
	proto.RegisterType((*ServerSpec)(nil), "lb.api.v1.ServerSpec")
	proto.RegisterType((*ServerPort)(nil), "lb.api.v1.ServerPort")
	proto.RegisterType((*ServerStatus)(nil), "lb.api.v1.ServerStatus")
	proto.RegisterType((*ServerIngress)(nil), "lb.api.v1.ServerIngress")
	proto.RegisterType((*ServerListRequest)(nil), "lb.api.v1.ServerListRequest")
	proto.RegisterType((*ServerShowRequest)(nil), "lb.api.v1.ServerShowRequest")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7) }

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0xbe, 0xa6, 0x69, 0xbc, 0x4c, 0xab, 0x72, 0x73, 0x1e, 0x86, 0x70, 0x60, 0xd9, 0x97, 0xab,
	0x08, 0xb9, 0x36, 0x8a, 0x20, 0xe8, 0x8b, 0xe7, 0x8b, 0xa0, 0x28, 0x5b, 0x44, 0xf0, 0x2d, 0x4d,
	0x47, 0x5d, 0x69, 0xb3, 0x6b, 0x76, 0xaf, 0xfa, 0x4f, 0xfc, 0x69, 0xfe, 0x1d, 0xc9, 0x6e, 0xd3,
	0x8b, 0x6e, 0x1f, 0xea, 0x4b, 0xd9, 0x7e, 0xdf, 0x37, 0xdf, 0x7c, 0x93, 0x19, 0x18, 0x69, 0xaa,
	0x37, 0x54, 0x67, 0xaa, 0x96, 0x46, 0x62, 0xbc, 0x5a, 0x64, 0x85, 0x12, 0xd9, 0x66, 0x96, 0xc2,
	0x9a, 0x4c, 0xe1, 0xe0, 0xf4, 0x6e, 0x29, 0xab, 0xa5, 0x30, 0x42, 0x56, 0x0e, 0x60, 0x9f, 0x01,
	0xe6, 0xb6, 0xee, 0x8d, 0xd0, 0x06, 0x2f, 0xe1, 0xb8, 0x11, 0x2f, 0x0b, 0x53, 0x24, 0xbd, 0x71,
	0x6f, 0x32, 0xcc, 0x4f, 0xb3, 0x9d, 0x51, 0xd6, 0x48, 0xde, 0x92, 0x29, 0xf8, 0x4e, 0x84, 0x17,
	0x30, 0x10, 0x86, 0xd6, 0x3a, 0x09, 0xc6, 0xfd, 0xc9, 0x30, 0x3f, 0xe9, 0xa8, 0x9d, 0x2d, 0x77,
	0x3c, 0xfb, 0xd5, 0x83, 0xc8, 0x21, 0x38, 0xf3, 0x9a, 0x9c, 0x75, 0xca, 0xde, 0x2d, 0xbe, 0x51,
	0xf9, 0x6f, 0x9b, 0x87, 0x10, 0x6a, 0x45, 0x65, 0x12, 0x78, 0x72, 0xe7, 0x39, 0x57, 0x54, 0x72,
	0x2b, 0xc1, 0x4b, 0x88, 0xb4, 0x29, 0xcc, 0xb5, 0x4e, 0xfa, 0x56, 0x7c, 0xdf, 0x17, 0x5b, 0x9a,
	0x6f, 0x65, 0xec, 0x63, 0xfb, 0x05, 0x1a, 0x13, 0x3c, 0x87, 0x98, 0xaa, 0xa5, 0x92, 0xa2, 0x32,
	0x3a, 0xe9, 0x8d, 0xfb, 0x93, 0x98, 0xdf, 0x00, 0xf8, 0x08, 0x06, 0x4a, 0xd6, 0xa6, 0x1d, 0xd7,
	0x0f, 0xf2, 0x5e, 0xd6, 0x86, 0x3b, 0x0d, 0x7b, 0xde, 0x1a, 0x37, 0x20, 0x22, 0x84, 0x0d, 0x6c,
	0x27, 0x1e, 0x70, 0xfb, 0xc6, 0x14, 0x8e, 0xed, 0x16, 0x4a, 0xb9, 0xb2, 0xa3, 0xc5, 0x7c, 0xf7,
	0x9f, 0xfd, 0x84, 0x51, 0x37, 0x2e, 0x3e, 0x01, 0xd8, 0xed, 0xce, 0x25, 0x1b, 0xe6, 0xf7, 0x3a,
	0xfd, 0xaf, 0x5a, 0x92, 0x77, 0x74, 0x98, 0xc3, 0x2d, 0x51, 0x7d, 0xa9, 0x49, 0xb7, 0x91, 0x13,
	0x2f, 0xf2, 0x6b, 0xc7, 0xf3, 0x56, 0xc8, 0x1e, 0xc0, 0xed, 0xbf, 0x18, 0xbc, 0x03, 0x81, 0x50,
	0x36, 0x78, 0xcc, 0x03, 0xa1, 0xd8, 0x29, 0x9c, 0xdc, 0xdc, 0x0c, 0xa7, 0xef, 0xd7, 0xa4, 0x0d,
	0xbb, 0x68, 0xc1, 0xf9, 0x57, 0xf9, 0x63, 0x0b, 0x36, 0x43, 0x57, 0xc5, 0x9a, 0xb6, 0xb5, 0xf6,
	0x9d, 0xff, 0x0e, 0x5a, 0xff, 0xe6, 0x57, 0x94, 0x84, 0x53, 0x88, 0xae, 0x6a, 0x2a, 0x0c, 0xa1,
	0x7f, 0x3f, 0xa9, 0x0f, 0xb1, 0x23, 0x7c, 0x01, 0xa1, 0xbd, 0xd7, 0x73, 0x8f, 0xec, 0x44, 0x4a,
	0xcf, 0xf6, 0xb2, 0xec, 0x08, 0x9f, 0x41, 0xd8, 0xa4, 0xdc, 0x53, 0xde, 0x09, 0xbf, 0xbf, 0xf3,
	0x14, 0xa2, 0x0f, 0x6a, 0xf9, 0x3f, 0x59, 0x9f, 0xc2, 0xc8, 0x55, 0x6c, 0x17, 0x79, 0x68, 0xdd,
	0x14, 0xa2, 0x57, 0xb4, 0xa2, 0xc3, 0x3b, 0xbd, 0x0c, 0x3f, 0x05, 0x9b, 0xd9, 0x22, 0xb2, 0x27,
	0xf4, 0xf8, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x76, 0x93, 0x2e, 0x70, 0x10, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServerServiceClient is the client API for ServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerServiceClient interface {
	Create(ctx context.Context, in *Server, opts ...grpc.CallOption) (*Server, error)
	List(ctx context.Context, in *ServerListRequest, opts ...grpc.CallOption) (*ServerList, error)
	Show(ctx context.Context, in *ServerShowRequest, opts ...grpc.CallOption) (*Server, error)
	Update(ctx context.Context, in *Server, opts ...grpc.CallOption) (*Server, error)
	UpdateStatus(ctx context.Context, in *Server, opts ...grpc.CallOption) (*Server, error)
	Delete(ctx context.Context, in *Server, opts ...grpc.CallOption) (*Server, error)
}

type serverServiceClient struct {
	cc *grpc.ClientConn
}

func NewServerServiceClient(cc *grpc.ClientConn) ServerServiceClient {
	return &serverServiceClient{cc}
}

func (c *serverServiceClient) Create(ctx context.Context, in *Server, opts ...grpc.CallOption) (*Server, error) {
	out := new(Server)
	err := c.cc.Invoke(ctx, "/lb.api.v1.ServerService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverServiceClient) List(ctx context.Context, in *ServerListRequest, opts ...grpc.CallOption) (*ServerList, error) {
	out := new(ServerList)
	err := c.cc.Invoke(ctx, "/lb.api.v1.ServerService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverServiceClient) Show(ctx context.Context, in *ServerShowRequest, opts ...grpc.CallOption) (*Server, error) {
	out := new(Server)
	err := c.cc.Invoke(ctx, "/lb.api.v1.ServerService/Show", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverServiceClient) Update(ctx context.Context, in *Server, opts ...grpc.CallOption) (*Server, error) {
	out := new(Server)
	err := c.cc.Invoke(ctx, "/lb.api.v1.ServerService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverServiceClient) UpdateStatus(ctx context.Context, in *Server, opts ...grpc.CallOption) (*Server, error) {
	out := new(Server)
	err := c.cc.Invoke(ctx, "/lb.api.v1.ServerService/UpdateStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverServiceClient) Delete(ctx context.Context, in *Server, opts ...grpc.CallOption) (*Server, error) {
	out := new(Server)
	err := c.cc.Invoke(ctx, "/lb.api.v1.ServerService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServiceServer is the server API for ServerService service.
type ServerServiceServer interface {
	Create(context.Context, *Server) (*Server, error)
	List(context.Context, *ServerListRequest) (*ServerList, error)
	Show(context.Context, *ServerShowRequest) (*Server, error)
	Update(context.Context, *Server) (*Server, error)
	UpdateStatus(context.Context, *Server) (*Server, error)
	Delete(context.Context, *Server) (*Server, error)
}

// UnimplementedServerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServerServiceServer struct {
}

func (*UnimplementedServerServiceServer) Create(ctx context.Context, req *Server) (*Server, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedServerServiceServer) List(ctx context.Context, req *ServerListRequest) (*ServerList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedServerServiceServer) Show(ctx context.Context, req *ServerShowRequest) (*Server, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Show not implemented")
}
func (*UnimplementedServerServiceServer) Update(ctx context.Context, req *Server) (*Server, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedServerServiceServer) UpdateStatus(ctx context.Context, req *Server) (*Server, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (*UnimplementedServerServiceServer) Delete(ctx context.Context, req *Server) (*Server, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterServerServiceServer(s *grpc.Server, srv ServerServiceServer) {
	s.RegisterService(&_ServerService_serviceDesc, srv)
}

func _ServerService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Server)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.api.v1.ServerService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServiceServer).Create(ctx, req.(*Server))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.api.v1.ServerService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServiceServer).List(ctx, req.(*ServerListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerService_Show_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServiceServer).Show(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.api.v1.ServerService/Show",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServiceServer).Show(ctx, req.(*ServerShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Server)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.api.v1.ServerService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServiceServer).Update(ctx, req.(*Server))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerService_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Server)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServiceServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.api.v1.ServerService/UpdateStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServiceServer).UpdateStatus(ctx, req.(*Server))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Server)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.api.v1.ServerService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServiceServer).Delete(ctx, req.(*Server))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lb.api.v1.ServerService",
	HandlerType: (*ServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ServerService_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ServerService_List_Handler,
		},
		{
			MethodName: "Show",
			Handler:    _ServerService_Show_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ServerService_Update_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _ServerService_UpdateStatus_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ServerService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
